export const field = {

    EMAIL: {
        name: "email",
        type: "email",
        title: "Почта",
        value: 'profile.email',
        placeholder: "Укажите свою почту",
        store: 'profile.email',
    },
    PHONE: {
        name: "phone",
        type: "tel",
        title: "Телефон",
        value: 'profile.phone',
        placeholder: "+7...",
        store: 'profile.phone',
    },
    FIRST_NAME: {
        name: "first_name",
        type: "text",
        title: "Имя",
        value: 'profile.first_name',
        placeholder: "...",
        store: 'profile.first_name',
    },
    SECOND_NAME: {
        name: "second_name",
        type: "text",
        title: "Фамилия",
        value: 'profile.second_name',
        placeholder: "...",
        store: 'profile.second_name',
    },
    DISPLAY_NAME: {
        name: "display_name",
        type: "text",
        title: "display_name",
        value: 'profile.display_name',
        placeholder: "...",
        store: 'profile.display_name',
    },
    LOGIN: {
        name: "login",
        type: "login",
        title: "Логин",
        value: 'profile.login',
        placeholder: "Укажите свой логин или кл...",
        store: 'profile.login',
    },
    LOGIN_CLEAR: {
        name: "login",
        type: "login",
        title: "Логин",
        value: '',
        placeholder: "Укажите свой логин или кл...",
    },
    PSW: {
        name: "password",
        type: "password",
        title: "Пароль",
        value: '',
        placeholder: "@#)**^_!~",
    },
    PSW_REPL: {
        name: "passwordRepl",
        type: "password",
        title: "Повторите пароль",
        value: '',
        placeholder: "@#)**^_!~",
    },
    PSW_CUR: {
        name: "passwordCur",
        type: "password",
        title: "Текущий пароль",
        value: '',
        placeholder: "@#)*$^_!~",
    },
    PSW_NEW: {
        name: "passwordNew",
        type: "password",
        title: "Новый пароль",
        value: '',
        placeholder: "@#)*$^_!~",
    },
    AVATAR: {
        title: "Изображение профиля",
        avatar: '',
        name: "avatar",
        image: 'true',
        store: 'profile.avatar',
    }
}
